/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    jobs: Job;
    media: Media;
    testimonials: Testimonial;
    galleries: Gallery;
    'map-locations': MapLocation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'map-locations': MapLocationsSelect<false> | MapLocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt' | 'en') | ('pt' | 'en')[];
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'ald-bioenergia-page': AldBioenergiaPage;
    'lavoura-page': LavouraPage;
    'centro-pesquisa-page': CentroPesquisaPage;
    'palestras-page': PalestrasPage;
    'careers-page': CareersPage;
    'contact-settings': ContactSetting;
    'footer-settings': FooterSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'ald-bioenergia-page': AldBioenergiaPageSelect<false> | AldBioenergiaPageSelect<true>;
    'lavoura-page': LavouraPageSelect<false> | LavouraPageSelect<true>;
    'centro-pesquisa-page': CentroPesquisaPageSelect<false> | CentroPesquisaPageSelect<true>;
    'palestras-page': PalestrasPageSelect<false> | PalestrasPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
  };
  locale: 'pt' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administrador pode criar e excluir usuários. Editor só edita conteúdo.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Dica: Use Enter para definir onde as linhas devem quebrar no card do site.
   */
  title: string;
  /**
   * Gerado automaticamente. Usado na URL: /servicos/consultoria-agronomica
   */
  slug?: string | null;
  /**
   * Aparece nos cards da lista de serviços. Dica: Use Enter para quebras de linha.
   */
  shortDescription: string;
  /**
   * Texto principal exibido à esquerda da imagem ilustrativa.
   */
  leftContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Texto secundário exibido abaixo da imagem ilustrativa (largura total).
   */
  bottomContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Opcional. Exibida em tablets (telas de até 1024px). Se não informada, usa a de Desktop.
   */
  coverImageTablet?: (number | null) | Media;
  /**
   * Opcional. Exibida em celulares (telas de até 580px). Se não informada, usa a de Desktop ou Tablet.
   */
  coverImageMobile?: (number | null) | Media;
  /**
   * Imagem exibida ao lado do texto principal da página de detalhes.
   */
  illustrationImage?: (number | null) | Media;
  /**
   * Se ativado, exibe a imagem ilustrativa ao lado do texto. Se desativado, o texto ocupa a largura total (Layout Sem Imagem).
   */
  showIllustration?: boolean | null;
  /**
   * Se ativado, renderiza uma seção com o anel animado de etapas no final da página (desenvolvido originalmente para a página de Agricultura de Precisão).
   */
  cycleActive?: boolean | null;
  /**
   * Cor em formato Hexadecimal para a borda do anel e número da etapa. Padrão: #88a668
   */
  cycleColor?: string | null;
  /**
   * Cor em formato Hexadecimal para o texto em destaque da etapa. Padrão: #88a668
   */
  cycleAccentColor?: string | null;
  cycleSteps?:
    | {
        /**
         * Ex: 1, 2, A, B...
         */
        stepNumber: string;
        /**
         * Ex: Preparo do
         */
        titleDark: string;
        /**
         * Ex: Solo
         */
        titleLight: string;
        desc: string;
        /**
         * Nome do ícone do Material Icons (Ex: agriculture, eco, biotech, warehouse, settings). Consulte: https://fonts.google.com/icons
         */
        icon: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para leitores de tela. Ex: "Campo de soja ao amanhecer"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Texto curto exibido no card da vaga. Máximo 200 caracteres.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  status: 'open' | 'paused' | 'closed';
  /**
   * Se marcado, a vaga será exibida na listagem do site.
   */
  visible?: boolean | null;
  openingDate?: string | null;
  /**
   * Opcional. Apenas para controle interno.
   */
  closingDate?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  authorName: string;
  /**
   * Ex: Grupo Mantovani • Sorriso - MT
   */
  authorDescription: string;
  photo?: (number | null) | Media;
  quote: string;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  slug?: string | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pins exibidos no mapa SVG. As coordenadas são pixels, não lat/lng.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-locations".
 */
export interface MapLocation {
  id: number;
  /**
   * Nome na lista
   */
  title: string;
  /**
   * Nome no mapa
   */
  city: string;
  state?: string | null;
  /**
   * Ex: 15.600 Hac.
   */
  area?: string | null;
  description?: string | null;
  /**
   * Eixo horizontal no SVG do mapa.
   */
  positionX: number;
  /**
   * Eixo vertical no SVG do mapa.
   */
  positionY: number;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'map-locations';
        value: number | MapLocation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  leftContent?: T;
  bottomContent?: T;
  coverImage?: T;
  coverImageTablet?: T;
  coverImageMobile?: T;
  illustrationImage?: T;
  showIllustration?: T;
  cycleActive?: T;
  cycleColor?: T;
  cycleAccentColor?: T;
  cycleSteps?:
    | T
    | {
        stepNumber?: T;
        titleDark?: T;
        titleLight?: T;
        desc?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  status?: T;
  visible?: T;
  openingDate?: T;
  closingDate?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  authorName?: T;
  authorDescription?: T;
  photo?: T;
  quote?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-locations_select".
 */
export interface MapLocationsSelect<T extends boolean = true> {
  title?: T;
  city?: T;
  state?: T;
  area?: T;
  description?: T;
  positionX?: T;
  positionY?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Dica: Use Enter para definir exatamente onde as linhas devem quebrar no site.
   */
  heroTitle?: string | null;
  /**
   * Dica: Use Enter para definir exatamente onde as linhas devem quebrar no site.
   */
  heroSubtitle?: string | null;
  /**
   * Escolha se deseja enviar uma imagem/vídeo direto ou utilizar um vídeo em loop do Vimeo.
   */
  heroMediaType?: ('upload' | 'vimeo') | null;
  /**
   * Cole o link do vídeo do Vimeo (ex: https://vimeo.com/76979871). O vídeo rodará automaticamente em loop contínuo e sem som.
   */
  heroVimeoUrl?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Opcional. Exibida em tablets (telas de até 1024px). Se não informada, usa a de Desktop.
   */
  heroImageTablet?: (number | null) | Media;
  /**
   * Opcional. Exibida em celulares (telas de até 580px). Se não informada, usa a de Desktop ou Tablet.
   */
  heroImageMobile?: (number | null) | Media;
  heroCtaLabel?: string | null;
  heroCtaUrl?: string | null;
  heroLogos?:
    | {
        logo: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  introTitle?: string | null;
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Escolha se deseja enviar uma imagem/vídeo direto ou utilizar um vídeo em loop do Vimeo.
   */
  introMediaType?: ('upload' | 'vimeo') | null;
  /**
   * Cole o link do vídeo do Vimeo (ex: https://vimeo.com/76979871). O vídeo rodará automaticamente em loop contínuo e sem som.
   */
  introVimeoUrl?: string | null;
  introImage?: (number | null) | Media;
  /**
   * Porcentagem da coluna ocupada pelo vídeo. Padrão: 80%.
   */
  introVideoWidth?: number | null;
  /**
   * 0 = sem limite (usa somente o % da coluna). Valores maiores permitem 16:9 mais impactante. Ex: 600 para proporção paisagem.
   */
  introVideoMaxWidth?: number | null;
  /**
   * Posição do vídeo na coluna direita. "Direita" garante bom afastamento do texto.
   */
  introVideoAlign?: ('right' | 'center' | 'left') | null;
  /**
   * Formato do vídeo. Define se ele é quadrado, retangular ou vertical.
   */
  introVideoAspectRatio?: ('16/9' | '1/1' | '4/5' | '9/16' | '4/3') | null;
  /**
   * Raio dos cantos do container externo (borda/fundo). 0 = sem arredondamento.
   */
  introVideoRadius?: number | null;
  /**
   * Arredonda os cantos do próprio vídeo (clip interno). Independente do container.
   */
  introVideoInnerRadius?: number | null;
  /**
   * Cor exibida ao redor do vídeo dentro do container. Ex: #f5f5f5. Deixe vazio para transparente.
   */
  introContainerBg?: string | null;
  /**
   * Espaço entre o vídeo e a borda do container.
   */
  introContainerPadding?: number | null;
  /**
   * Ativa uma borda visível ao redor do container de vídeo.
   */
  introContainerBorder?: boolean | null;
  /**
   * Cor da borda do container. Ex: #cccccc.
   */
  introContainerBorderColor?: string | null;
  introCtaLabel?: string | null;
  introCtaUrl?: string | null;
  /**
   * Ex: "Sua próxima safra, pode ser ainda". Dica: Use Enter para definir as quebras de linha.
   */
  bannerText?: string | null;
  bannerTextAlign?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Ex: "melhor conosco!". Dica: Use Enter para definir as quebras de linha.
   */
  bannerTextAccent?: string | null;
  /**
   * Cor em formato Hexadecimal para o texto em destaque. Padrão: #e1fe00
   */
  bannerTextAccentColor?: string | null;
  bannerImage?: (number | null) | Media;
  /**
   * Ex: Resultados
   */
  statsTag?: string | null;
  /**
   * Ex: Números que
   */
  statsTitle?: string | null;
  /**
   * Ex: traduzem excelência — aparecerá em verde
   */
  statsTitleAccent?: string | null;
  /**
   * Cor em formato Hexadecimal para o título destacado. Padrão: #88a668
   */
  statsTitleAccentColor?: string | null;
  statsTitleAlign?: ('left' | 'center' | 'right' | 'justify') | null;
  /**
   * Dica: Use Enter para definir as quebras de linha.
   */
  statsSubtext?: string | null;
  statsSubtextAlign?: ('left' | 'center' | 'right' | 'justify') | null;
  stats?:
    | {
        /**
         * Ex: +
         */
        prefix?: string | null;
        value: number;
        /**
         * Ex: m, k
         */
        suffix?: string | null;
        /**
         * Ex: Hectares atendidos
         */
        label: string;
        icon?: (number | null) | Media;
        /**
         * Escolha uma paleta de cores pré-definida ou selecione "Personalizado" para inserir cores sob medida.
         */
        color?:
          | (
              | 'peach'
              | 'dark'
              | 'lime'
              | 'paleGreen'
              | 'bronze'
              | 'forest'
              | 'white'
              | 'gray'
              | 'softYellow'
              | 'softBlue'
              | 'custom'
            )
          | null;
        /**
         * Ex: #ffd087
         */
        customBgColor?: string | null;
        /**
         * Ex: #965a30
         */
        customTextColor?: string | null;
        id?: string | null;
      }[]
    | null;
  methodologyBadge?: string | null;
  /**
   * Dica: Use Enter para definir as quebras de linha.
   */
  methodologyTitle?: string | null;
  methodologyTitleAlign?: ('left' | 'center' | 'right' | 'justify') | null;
  methodologyCards?:
    | {
        title: string;
        description: string;
        icon?: (number | null) | Media;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex: Atuação
   */
  mapTag?: string | null;
  mapTitle?: string | null;
  mapDescription?: string | null;
  mapLogos?:
    | {
        logo: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex: Parceria
   */
  galleryTitle?: string | null;
  gallerySubtitle?: string | null;
  galleryImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex: Depoimentos
   */
  testimonialsTag?: string | null;
  /**
   * Ex: A escolha dos líderes
   */
  testimonialsTitle?: string | null;
  /**
   * Ex: que inovam no campo — aparecerá em verde
   */
  testimonialsTitleAccent?: string | null;
  ctaText?: string | null;
  ctaButtonLabel?: string | null;
  ctaButtonUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Opcional. Exibida em tablets (telas de até 1024px). Se não informada, usa a de Desktop.
   */
  heroImageTablet?: (number | null) | Media;
  /**
   * Opcional. Exibida em celulares (telas de até 580px). Se não informada, usa a de Desktop ou Tablet.
   */
  heroImageMobile?: (number | null) | Media;
  /**
   * Ex: Quem Somos
   */
  introTag?: string | null;
  /**
   * Título principal. Dica: Use Enter para quebras de linha.
   */
  title?: string | null;
  /**
   * Subtítulo em destaque. Dica: Use Enter para quebras de linha.
   */
  subtitle?: string | null;
  /**
   * Cor em formato Hexadecimal para o texto em destaque. Padrão: #88a668
   */
  subtitleColor?: string | null;
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  commitment?: {
    title?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  vision?: {
    title?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  values?: {
    title?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Ex: Vídeo Institucional
   */
  videoSectionTag?: string | null;
  videoSectionTitle?: string | null;
  videoSectionTitleAccent?: string | null;
  /**
   * Cor em formato Hexadecimal para o título destacado. Padrão: #88a668
   */
  videoSectionTitleAccentColor?: string | null;
  /**
   * Cole a URL de embed do YouTube. Ex: https://www.youtube.com/embed/XXXXXXXXX
   */
  institutionalVideoUrl?: string | null;
  /**
   * Ex: Nossa História
   */
  timelineTag?: string | null;
  timelineTitle?: string | null;
  timeline?:
    | {
        /**
         * Ex: o início, consultoria
         */
        tag: string;
        /**
         * Ex: 1993, Atual
         */
        year: string;
        text: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Opcional. Exibida em tablets (telas de até 1024px). Se não informada, usa a de Desktop.
   */
  heroImageTablet?: (number | null) | Media;
  /**
   * Opcional. Exibida em celulares (telas de até 580px). Se não informada, usa a de Desktop ou Tablet.
   */
  heroImageMobile?: (number | null) | Media;
  servicesBadge?: string | null;
  /**
   * Dica: Use Enter para quebras de linha.
   */
  servicesTitle?: string | null;
  /**
   * Dica: Use Enter para quebras de linha.
   */
  servicesSubtitle?: string | null;
  /**
   * Cor em formato Hexadecimal para o texto em destaque. Padrão: #88a668
   */
  servicesSubtitleColor?: string | null;
  /**
   * Dica: Use Enter para quebras de linha.
   */
  servicesDescription?: string | null;
  servicesCards?:
    | {
        /**
         * Dica: Use Enter para definir onde as linhas devem quebrar no card.
         */
        title: string;
        /**
         * Dica: Use Enter para quebras de linha no card.
         */
        shortDescription: string;
        /**
         * Ex: consultoria-agronomica, unita, agricultura-de-precisao, gestao-de-compras, pesquisa-agronomica
         */
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  ecosystemBadge?: string | null;
  /**
   * Dica: Use Enter para quebras de linha.
   */
  ecosystemTitle?: string | null;
  /**
   * Dica: Use Enter para quebras de linha.
   */
  ecosystemSubtitle?: string | null;
  /**
   * Cor em formato Hexadecimal para o texto em destaque. Padrão: #88a668
   */
  ecosystemSubtitleColor?: string | null;
  ecosystemCards?:
    | {
        title: string;
        image?: (number | null) | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ald-bioenergia-page".
 */
export interface AldBioenergiaPage {
  id: number;
  heroImage: number | Media;
  title: string;
  leftContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  logoImage: number | Media;
  indicators?:
    | {
        value: string;
        description: string;
        icon: number | Media;
        theme: 'dark' | 'lime' | 'light';
        id?: string | null;
      }[]
    | null;
  section3Content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  section3Image: number | Media;
  bottomContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lavoura-page".
 */
export interface LavouraPage {
  id: number;
  heroImage: number | Media;
  title: string;
  leftContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: number | Media;
  bottomContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "centro-pesquisa-page".
 */
export interface CentroPesquisaPage {
  id: number;
  heroImage: number | Media;
  title: string;
  leftContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palestras-page".
 */
export interface PalestrasPage {
  id: number;
  heroImage: number | Media;
  title: string;
  leftContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Opcional. Exibida em tablets (telas de até 1024px). Se não informada, usa a de Desktop.
   */
  heroImageTablet?: (number | null) | Media;
  /**
   * Opcional. Exibida em celulares (telas de até 580px). Se não informada, usa a de Desktop ou Tablet.
   */
  heroImageMobile?: (number | null) | Media;
  /**
   * Exemplo: "Faça parte "
   */
  title?: string | null;
  /**
   * Exemplo: "da PA"
   */
  titleHighlight?: string | null;
  /**
   * Cor em formato Hexadecimal para o texto em destaque. Padrão: #88a668
   */
  titleHighlightColor?: string | null;
  /**
   * Texto exibido logo abaixo do título principal. Dica: Use Enter para quebras de linha.
   */
  introText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  heroImage?: (number | null) | Media;
  /**
   * Opcional. Exibida em tablets (telas de até 1024px). Se não informada, usa a de Desktop.
   */
  heroImageTablet?: (number | null) | Media;
  /**
   * Opcional. Exibida em celulares (telas de até 580px). Se não informada, usa a de Desktop ou Tablet.
   */
  heroImageMobile?: (number | null) | Media;
  /**
   * Recebe as mensagens enviadas pelo formulário da página Contato.
   */
  formRecipientEmail?: string | null;
  /**
   * Recebe as candidaturas enviadas pela página Carreiras.
   */
  careerRecipientEmail?: string | null;
  /**
   * Ex: (65) 3016-1203
   */
  phone?: string | null;
  /**
   * Número com DDD, sem formatação. Ex: 65991234567
   */
  whatsapp?: string | null;
  formTitle?: string | null;
  formDescription?: string | null;
  addresses?:
    | {
        /**
         * Ex: Grupo PA - Matriz
         */
        title: string;
        address?: string | null;
        phone?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: number;
  /**
   * Cadastre os endereços e os links correspondentes do Google Maps que serão exibidos no rodapé do site.
   */
  addresses: {
    /**
     * Ex: Matriz Tangará
     */
    label: string;
    text: string;
    mapsUrl: string;
    id?: string | null;
  }[];
  linkedinUrl?: string | null;
  instagramUrl?: string | null;
  facebookUrl?: string | null;
  youtubeUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroMediaType?: T;
  heroVimeoUrl?: T;
  heroImage?: T;
  heroImageTablet?: T;
  heroImageMobile?: T;
  heroCtaLabel?: T;
  heroCtaUrl?: T;
  heroLogos?:
    | T
    | {
        logo?: T;
        alt?: T;
        id?: T;
      };
  introTitle?: T;
  introText?: T;
  introMediaType?: T;
  introVimeoUrl?: T;
  introImage?: T;
  introVideoWidth?: T;
  introVideoMaxWidth?: T;
  introVideoAlign?: T;
  introVideoAspectRatio?: T;
  introVideoRadius?: T;
  introVideoInnerRadius?: T;
  introContainerBg?: T;
  introContainerPadding?: T;
  introContainerBorder?: T;
  introContainerBorderColor?: T;
  introCtaLabel?: T;
  introCtaUrl?: T;
  bannerText?: T;
  bannerTextAlign?: T;
  bannerTextAccent?: T;
  bannerTextAccentColor?: T;
  bannerImage?: T;
  statsTag?: T;
  statsTitle?: T;
  statsTitleAccent?: T;
  statsTitleAccentColor?: T;
  statsTitleAlign?: T;
  statsSubtext?: T;
  statsSubtextAlign?: T;
  stats?:
    | T
    | {
        prefix?: T;
        value?: T;
        suffix?: T;
        label?: T;
        icon?: T;
        color?: T;
        customBgColor?: T;
        customTextColor?: T;
        id?: T;
      };
  methodologyBadge?: T;
  methodologyTitle?: T;
  methodologyTitleAlign?: T;
  methodologyCards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        image?: T;
        id?: T;
      };
  mapTag?: T;
  mapTitle?: T;
  mapDescription?: T;
  mapLogos?:
    | T
    | {
        logo?: T;
        alt?: T;
        id?: T;
      };
  galleryTitle?: T;
  gallerySubtitle?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  testimonialsTag?: T;
  testimonialsTitle?: T;
  testimonialsTitleAccent?: T;
  ctaText?: T;
  ctaButtonLabel?: T;
  ctaButtonUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageTablet?: T;
  heroImageMobile?: T;
  introTag?: T;
  title?: T;
  subtitle?: T;
  subtitleColor?: T;
  introText?: T;
  commitment?:
    | T
    | {
        title?: T;
        text?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        text?: T;
      };
  values?:
    | T
    | {
        title?: T;
        text?: T;
      };
  videoSectionTag?: T;
  videoSectionTitle?: T;
  videoSectionTitleAccent?: T;
  videoSectionTitleAccentColor?: T;
  institutionalVideoUrl?: T;
  timelineTag?: T;
  timelineTitle?: T;
  timeline?:
    | T
    | {
        tag?: T;
        year?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageTablet?: T;
  heroImageMobile?: T;
  servicesBadge?: T;
  servicesTitle?: T;
  servicesSubtitle?: T;
  servicesSubtitleColor?: T;
  servicesDescription?: T;
  servicesCards?:
    | T
    | {
        title?: T;
        shortDescription?: T;
        slug?: T;
        id?: T;
      };
  ecosystemBadge?: T;
  ecosystemTitle?: T;
  ecosystemSubtitle?: T;
  ecosystemSubtitleColor?: T;
  ecosystemCards?:
    | T
    | {
        title?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ald-bioenergia-page_select".
 */
export interface AldBioenergiaPageSelect<T extends boolean = true> {
  heroImage?: T;
  title?: T;
  leftContent?: T;
  logoImage?: T;
  indicators?:
    | T
    | {
        value?: T;
        description?: T;
        icon?: T;
        theme?: T;
        id?: T;
      };
  section3Content?: T;
  section3Image?: T;
  bottomContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lavoura-page_select".
 */
export interface LavouraPageSelect<T extends boolean = true> {
  heroImage?: T;
  title?: T;
  leftContent?: T;
  image?: T;
  bottomContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "centro-pesquisa-page_select".
 */
export interface CentroPesquisaPageSelect<T extends boolean = true> {
  heroImage?: T;
  title?: T;
  leftContent?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palestras-page_select".
 */
export interface PalestrasPageSelect<T extends boolean = true> {
  heroImage?: T;
  title?: T;
  leftContent?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageTablet?: T;
  heroImageMobile?: T;
  title?: T;
  titleHighlight?: T;
  titleHighlightColor?: T;
  introText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroImageTablet?: T;
  heroImageMobile?: T;
  formRecipientEmail?: T;
  careerRecipientEmail?: T;
  phone?: T;
  whatsapp?: T;
  formTitle?: T;
  formDescription?: T;
  addresses?:
    | T
    | {
        title?: T;
        address?: T;
        phone?: T;
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  addresses?:
    | T
    | {
        label?: T;
        text?: T;
        mapsUrl?: T;
        id?: T;
      };
  linkedinUrl?: T;
  instagramUrl?: T;
  facebookUrl?: T;
  youtubeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}